### ISSUE TITLE
No standalone

### ISSUE THREAD

**Issue by k43r** [trekawek/radioblock#3]
Drogi Rękawku,
w wersji 3.1 Twojego projektu dostępny był plik standalone, który działał wspanialne. Niestety w tej wersji go nigdzie nie znajduję. Czy byłaby możliwość stworzenia takiego pliku również dla obecnej wersji ? Nie jestem osobą biegłą w linuksy ani javy i mimo prób nie udało mi się odpalić nowej wersji twojego projektu.

**Comment by trekawek** [comment]
Witam!
Utworzyłem githubowy release, jest dostępny tutaj:
https://github.com/trekawek/radioblock/releases/download/radioblock-parent-1.3.2/standalone-1.3.2.jar

Miłego słuchania!
